export const certificationNames = [
	'BRC Global Standard',
	'CE Marking',
	'COSMOS Organic and Natural',
	'Cruelty-Free Certification',
	'Energy Star',
	'Fair Trade Certification',
	'FCC Certification',
	'FSC Certification',
	'GOTS Certification',
	'HACCP',
	'Halal Certification',
	'ISO 9001',
	'ISO 14001',
	'ISO 22000',
	'ISO_TS 16949',
	'Kosher',
	'Non-GMO Certification',
	'OEKO-TEX Standart 100',
	'Organic Certification',
	'Rainforest Alliance Certifation',
	'RoHS Compliance',
	'WRAP Certification',
];
