image: node:16



pipelines:
  branches:
    dev:
      - step:
          name: Installing dependencies
          size: 2x
          caches:
            - node
          script:
            - echo "Installing dependencies..."
            - npm install --legacy-peer-deps
            - echo "Building Angular app..."
            - npm run build:ssr
            - echo "Successfully built"
          artifacts:
            - dist/**
      - step:
          name: Deploy to Server
          deployment: dev
          script:
            - echo "Setting up SSH..."
            - scp -r -P 22 dist/ discount@159.89.4.114:/home/discount/
            - ssh discount@159.89.4.114 'sh build-fe.sh'
            - echo "DEPLOYED"


